[package]
name = "rust-arduino-blink"
version = "0.1.0"

[profile.release]
panic = "abort"

[dependencies]
panic-halt = "0.2.0"

[dependencies.arduino-hal]
git = "https://github.com/Rahix/avr-hal"
rev = "8e4ba8f"
features = ["arduino-uno"]
